package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildRelease'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildRelease")) {
    expectSteps {
        gradle {
            tasks = "build publish"
            gradleParams = "-Pdeploy.version=%release.version% -Pdeploy.enabled=true -Pdeploy.repo-url=%deploy.repo-url% -Pdeploy.username=%deploy.username% -Pdeploy.password=%deploy.password% --scan --info"
        }
    }
    steps {
        insert(1) {
            step {
                name = "Create GitHub Release"
                id = "Create_GitHub_Release"
                type = "githubReleasesRunner"
                param("releaseTagName", "%release.version%")
                param("generateReleaseNotes", "true")
                param("isDraft", "true")
                param("vcsRootId", "Public_ComposeGl_ComposeGl")
                param("authenticationType", "vcsRoot")
                param("releaseTitle", "%release.version%")
            }
        }
    }
}
