package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        remove {
            githubConnection {
                id = "PROJECT_EXT_10"
                displayName = "GitHub.com"
                clientId = "Ov23liT97vPVEYmQSgyV"
                clientSecret = "credentialsJSON:caa167f1-c169-4bab-add1-445d1770fe1d"
            }
        }
    }
}
