name: "Publish release"
on:
  release:
    types: [ published ]
env:
  REPOSILITE_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
  REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}
  REPOSILITE_URL: "https://reposilite.silenium.dev/releases"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
          gradle-home-cache-cleanup: true
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
          add-job-summary-as-pr-comment: on-failure
      - name: Build with Gradle
        run: ./gradlew build -Pdeploy.version=${{github.ref_name}} publish --console=plain --info --build-cache --configure-on-demand --configuration-cache --parallel
